### PR TITLE
[Integration Manager] SFCC place order

### PR DESCRIPTION
**Pull request by jnurse**
This PR adds the submitPayment command to the SFCC connector. *Note* Currently we're able to create orders, but not get them to the confirmed status. 

 **JIRA**: https://mobify.atlassian.net/browse/WEBDATA-48
 **Linked PRs**: n/a

## Changes
- Add command to submitPayment on SFCC
- Add fetch Payment page command for SFCC
- Update createBasket util to return the full basket 

## How to test-drive this PR
- Run `npm run dev`
- Preview [the SFCC site](https://preview.mobify.com/?url=http%3A%2F%2Fmobify-tech-prtnr-na03-dw.demandware.net%2Fon%2Fdemandware.store%2FSites-2017refresh-Site%2Fdefault%2FHome-Show&site_folder=https%3A%2F%2Flocalhost%3A8443%2Floader.js&disabled=0&domain=&scope=1)
- Add an item to your cart and proceed through the checkout to the payment page
- Enter correct information on the page and place the order
- You should be taken to the confirmation page
- You should see your new order in the SFCC admin site

### CODE REVIEW

**Comment by DanielBrookRoberge** [comment]
If I've got a stale guest basket ID in my session storage, this PR doesn't clear and retry. Probably we aren't checking for the 400 status correctly?

**Comment by jnurse** [comment]
Thanks @DanielBrookRoberge I'll take a look. This branch actually has a bunch of bugs in it since I merged in the integration-manager branch, so I'll switch this PR back to WIP while I get these resolved.

**Comment by jnurse** [comment]
@DanielBrookRoberge I think this is broken on the integration-manager branch too. The command that's checking for a 404 and retrying is `requestCartData`, which the `addToCart` command doesn't use. The `addToCart` command doesn't have any logic to retry the command if it fails. 

We might want to make a util that handles all our basket/cart requests for SFCC that can have retry logic, but maybe that work can be done in a separate PR? That way we can focus on getting this merged and completing the order confirmation commands. What do you think?

**Comment by DanielBrookRoberge** [comment]
Yeah, let's fix that separately then, if it's not specific to this branch. So I'm :+1: for merging this.

**Pull request merged**
